CC = gcc
all:
	$(CC) -o IMT2022043_student_course_pds_tester IMT2022043_pds.c bst.c 

clean:
	rm IMT2022043_student_course_pds_tester newdemo_course.dat newdemo_student.dat newdemo_student.ndx newdemo_student_newdemo_course.dat interactive student.dat course.dat student_course.dat student.ndx

interactive:
	$(CC) -o interactive IMT2022043_pds.c bst.c linked_data_demo.c

run_interactive:
	./interactive